birds/urls.py
# -*- coding: utf-8 -*-
# -*- mode: python -*-
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import re_path

from birds import views

urlpatterns = [
    # browser ui

    re_path(r'^$', views.IndexView.as_view(), name='index'),

    # Birds
    #re_path(r'^animals/$', views.AnimalList.as_view(), name='animals'),
    re_path(r'^animals/$', views.AnimalTableList.as_view(), name='animals'),
    re_path(r'^animals_search/$', views.AnimalSearch.as_view(), name='animals_search'),
    re_path(r'^animals_search_display/$', views.AnimalSearchDisplay.as_view(), name='animals_search_display'),
    re_path(r'^animals/new/$', login_required(views.BandingEntry.as_view()), name='new_animal'),
    re_path(r'^animals/(?P<uuid>[a-f0-9\-]{36})/$', views.AnimalView.as_view(), name='animal'),

    # Events
    re_path(r'^animals/(?P<animal>[a-f0-9\-]{36})/events/$',
        views.EventList.as_view(), name='animal_events'),
    re_path(r'^animals/(?P<uuid>[a-f0-9\-]{36})/events/new/$',
        login_required(views.EventEntry.as_view()), name='new_event'),
    re_path(r'^animals/(?P<uuid>[a-f0-9\-]{36})/events/new/$',
        login_required(views.NestEventEntry.as_view()), name='new_event'),    
    re_path(r'^events/$', views.EventList.as_view(), name='events'),
        re_path(r'^events/new/$', login_required(views.EventEntry.as_view()), name='new_event'),

    # Nests
    re_path(r'^nests/$', views.NestTableList.as_view(), name='nests'),
    re_path(r'^nests/(?P<uuid>[a-f0-9\-]{36})/$', views.NestView.as_view(), name='nest'),
    re_path(r'^nests/(?P<uuid>[a-f0-9\-]{36})/events/new/$', login_required(views.NestEventEntry.as_view()), name='nest_event'),
    re_path(r'^nests/events/new/$', login_required(views.NestEventEntry.as_view()), name='nest_event'),

    # Eggs
    re_path(r'^eggs/$', views.EggTableList.as_view(), name='eggs'),
    re_path(r'^eggs/new/$', login_required(views.EggEntry.as_view()), name='new_eggs'),
    re_path(r'^eggs/(?P<uuid>[a-f0-9\-]{36})/$', views.EggView.as_view(), name='egg'),
    re_path(r'^eggs/(?P<uuid>[a-f0-9\-]{36})/events/new/$', login_required(views.EggEventEntry.as_view()), name='egg_event'),
    re_path(r'^eggs/events/new/$', login_required(views.EggEventEntry.as_view()), name='egg_event'),
    
    # Matings
    re_path(r'^matings/$', views.MatingTableList.as_view(), name='matings'),
        re_path(r'^matings/new/$', login_required(views.MatingEntry.as_view()), name='new_mating'),
    
    # Summary views
    re_path(r'^summary/events/([0-9]{4})/([0-9]{1,2})/$', views.EventSummary.as_view(),
        name="event_summary"),
    # forms
    re_path(r'^clutch$', login_required(views.ClutchEntry.as_view()), name='clutch'),
    # api
    re_path(r'^api/animals/$', views.APIAnimalsList.as_view(), name="animals_api"),
    re_path(r'^api/animals/(?P<pk>[a-f0-9\-]{36})/$', views.APIAnimalDetail.as_view()),
    #re_path(r'^api/animals/(?P<uuid>[a-f0-9\-]{36})/events$', views.APIEventsList.as_view()),
    re_path(r'^api/events/$', views.APIEventsList.as_view(), name="events_api"),
 
    ## LOGIN/LOGOUT
    re_path(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), {'next_page': 'birds:login'}, name='logout')
]

urlpatterns += staticfiles_urlpatterns()

birds/forms.py
# -*- coding: utf-8 -*-
# -*- mode: python -*-

import datetime
from django import forms

from django.contrib.auth.models import User
from birds.models import Animal, Event, Status, Location, Color, Species, GeneticParent, Parent, Nest, Mating, Claim, NestEvent, Egg, EggEvent, EggEventCode, ParentEgg

import ipdb

class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = ["animal", "date", "status", "location", "description", "entered_by"]

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)

        if len(self.initial.values())==3:
            self.fields['animal'] = forms.ModelChoiceField(queryset=(Animal.objects.filter(uuid__exact=self.initial.get('uuid'))))
        else:
            pass

    def create_event(self):
#        ipdb.set_trace()
        data = self.data
        if Status.objects.get(id=data['status']).name == 'moved':
            Animal.objects.filter(uuid=data['animal']).update(location=data['location'])


        #ipdb.set_trace()
        evt = Event(animal=Animal.objects.get(uuid=data['animal']),
                    date=data['date'],
                    status=Status.objects.get(id=data['status']),
                    description=data['description'],
                    location=Location.objects.get(id=data['location']),
                    entered_by=User.objects.get(id=data['entered_by']))
        evt.save()
        return(evt)
    
class NestEventForm(forms.ModelForm):   
    class Meta:
        model = NestEvent 
        fields = ["nest", "date", "event", "number",  "entered_by"]
        

    def __init__(self, *args, **kwargs):
        super(NestEventForm, self).__init__(*args, **kwargs)

class EggEventForm(forms.ModelForm):

    class Meta:
        model = EggEvent
        fields = ["egg", "date", "event", "location", "description", "entered_by"]

    def __init__(self, *args, **kwargs):
        super(EggEventForm, self).__init__(*args, **kwargs)
        #ipdb.set_trace()
        if len(self.initial.values())==4:
            
            egg_qs = Egg.objects.filter(uuid=self.initial.get('uuid'))
            egg_obj = egg_qs[0]
            self.fields['egg'] = forms.ModelChoiceField(queryset=egg_qs)
            
            current_location = egg_obj.location
            if current_location is None:
                current_location = egg_obj.nest
            self.fields['location'] = forms.ModelChoiceField(queryset = Location.objects.filter(name=self.initial.get('location')))
        else:
            pass

    def create_event(self):
#        ipdb.set_trace()
        data = self.data
        if Status.objects.get(id=data['event']).name == 'moved':
            Egg.objects.filter(uuid=data['egg']).update(location=data['location'])


        #ipdb.set_trace()
        evt = EggEvent(egg=Egg.objects.get(uuid=data['egg']),
                    date=data['date'],
                    event=EggEventCode.objects.get(id=data['event']),
                    description=data['description'],
                    location=Location.objects.get(id=data['location']),
                    entered_by=User.objects.get(id=data['entered_by']))
        evt.save()
        return(evt)
    
class BandingForm(forms.Form):
    acq_status = forms.ModelChoiceField(queryset=Status.objects.filter(count=1),
                                        initial=Status.objects.get(name__contains='hatched').id)
    acq_date = forms.DateField()
    sex = forms.ChoiceField(choices=(('M', 'male'),
                                     ('F', 'female'),
                                     ('U', 'unknown')))    
    seqvar = forms.ChoiceField(choices=(('yes','Y'),('no','N')),required=False)   
    repeats = forms.ChoiceField(choices=(('yes','Y'),('no','N')),required=False)
    nest = forms.ModelChoiceField(queryset=Nest.objects.all(), required=False)
    sire = forms.ModelChoiceField(queryset=Animal.objects.filter(sex__exact='M'),
                                  required=False)
    dam  = forms.ModelChoiceField(queryset=Animal.objects.filter(sex__exact='F'),
                                  required=False)
    geneticsire = forms.ModelChoiceField(queryset=Animal.objects.filter(sex__exact='M'),
                                  required=False)
    geneticdam  = forms.ModelChoiceField(queryset=Animal.objects.filter(sex__exact='F'),
                                  required=False)      
    species = forms.ModelChoiceField(queryset=Species.objects.all(), required=False,
                                     initial=Species.objects.get(code__exact='BF').id)
    banding_date = forms.DateField()
    band_color1 = forms.ModelChoiceField(queryset=Color.objects.all(), required=False)
    band_number1 = forms.IntegerField(min_value=1)
    band_color2 = forms.ModelChoiceField(queryset=Color.objects.all(), required=False)
    band_number2 = forms.IntegerField(min_value=1, required=False)
    location = forms.ModelChoiceField(queryset=Location.objects.all())
    comments = forms.CharField(widget=forms.Textarea, required=False)
    user = forms.ModelChoiceField(queryset=User.objects.all())

    def clean(self):
        super(BandingForm, self).clean()
        data = self.cleaned_data
        try:
            data['band_status'] = Status.objects.get(name__startswith="band")
        except:
            raise forms.ValidationError("No 'banded' status type - add one in admin")
        if 'acq_status' in data and data['acq_status'].name == "hatched":
            if (data['dam'] is None or data['sire'] is None) and data['nest'] is None:
                raise forms.ValidationError("Parents or Nest required for hatched birds")
            #if data['dam'].species != data['sire'].species:
            #    raise forms.ValidationError("Parents must be the same species")
            #data['species'] = data['dam'].species
        else:
            if data['species'] is None:
                raise forms.ValidationError("Species required for non-hatch acquisition")
            data['dam'] = None
            data['sire'] = None
        return data

    def create_chick(self):
        #ipdb.set_trace()
        data = self.cleaned_data
        band_list = map(lambda x : str(x), [data['band_color1'], data['band_number1'], data['band_color2'], data['band_number2']])
        band = band="".join(band_list)

        if data['acq_status'].name == 'hatched':
            hd = data['acq_date']
            if data['nest'] and not (data['sire'] or data['dam']):
                #ipdb.set_trace()
                nest_obj = Nest.objects.filter(name=data['nest'])[0]
                sire = nest_obj.current_mating().sire
                dam = nest_obj.current_mating().dam
            else:
                sire = data['sire']
                dam = data['dam']
        else:
            hd = None

        chick = Animal(species=data['species'], sex=data['sex'],
                       hatch_date=hd,
                       location=data['location'],
                       band_color=data['band_color1'], band_number=data['band_number1'],
                       band_color2=data['band_color2'], band_number2=data['band_number2'],   
                       nest=data['nest'])
        chick.save()
        chick.update_age_days()
        #birds.cron.update_age_days(chick)
        
        if data['acq_status'].name == 'hatched':
            Parent.objects.create(child=chick, parent=sire)
            Parent.objects.create(child=chick, parent=dam)
    
                    
        evt = Event(animal=chick, date=data['acq_date'],
                    status=data['acq_status'],
                    description=data['comments'],
                    location=data['location'],
                    entered_by=data['user'])
        evt.save()
        
        evt = Event(animal=chick, date=data['banding_date'],
                    status=data['band_status'],
                    location=data['location'],
                    description=chick.band,
                    entered_by=data['user'])
        evt.save()
        return chick


class ClutchForm(forms.Form):
    sire = forms.ModelChoiceField(queryset=Animal.objects.filter(sex__exact='M'), required=False)
    dam  = forms.ModelChoiceField(queryset=Animal.objects.filter(sex__exact='F'), required=False)
    geneticsire = forms.ModelChoiceField(queryset=Animal.objects.filter(sex__exact='M'), required=False)
    geneticdam  = forms.ModelChoiceField(queryset=Animal.objects.filter(sex__exact='F'), required=False)      
    nest = forms.ModelChoiceField(queryset=Nest.objects.all())
    chicks = forms.IntegerField(min_value=1)
    hatch_date = forms.DateField(initial=datetime.date.today)
    comments = forms.CharField(widget=forms.Textarea, required=False)
    user = forms.ModelChoiceField(queryset=User.objects.all())

    def clean(self):
        super(ClutchForm, self).clean()
        try:
            self.cleaned_data['status'] = Status.objects.get(name__startswith="hatch")
        except:
            raise forms.ValidationError("No 'hatch' status type - add one in admin")

        #if ('dam' in self.cleaned_data and 'sire' in self.cleaned_data and
        #    self.cleaned_data['dam'].species != self.cleaned_data['sire'].species):
        #    raise forms.ValidationError("Parents must be the same species")
        return self.cleaned_data


    def create_clutch(self):
        ret = {'chicks': [], 'events': []}
        
        for i in range(self.cleaned_data['chicks']):

            if self.cleaned_data['nest'] is not None:
                nest_obj = Nest.objects.filter(name=self.cleaned_data['nest'])[0]
                sire = nest_obj.current_mating().sire
                dam = nest_obj.current_mating().dam
    
                geneticsire = sire
                geneticdam = dam

            if self.cleaned_data['geneticsire'] is not None:
                geneticsire = self.cleaned_data['geneticsire']
                

birds/templates/birds/animals_search - Copy.html
{% extends "base.html" %}

{% load static %}
{% load widget_tweaks %}
{% load render_table from django_tables2 %}
{% load bootstrap3 %}
{% block title %} Colquitt lab : bird colony : add bird {% endblock title%}

<link href="{% static "datepicker/css/bootstrap-datetimepicker.min.css" %}" rel="stylesheet type='text/css'">
<!-- <link href="{% static 'admin/css/fonts.css' %}" rel="stylesheet">  -->

{% block scripts %}
<script src="{% static 'datepicker/js/moment.min.js' %}"></script> 
<script src="{% static 'datepicker/js/bootstrap-datetimepicker.min.js' %}"></script>
<script type="text/javascript">
  $(function () {
  $('#datetimepicker1').datetimepicker({ pickTime: false});
  $('#datetimepicker2').datetimepicker({ pickTime: false});
  });
</script>
{% endblock %}
{% block content %}

{% include "birds/home.html" %} 
<!--
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Bird search</h3>
  </div>
  <div class="panel-body">
    <!-- <form action="{% url 'birds:animals_search' %}" class="form-horizontal" method="post" role="form"> -->
    <form action="{% url 'birds:animals_search' %}" class="form-horizontal" method="get" role="form">
      {% csrf_token %}
      <p><strong>All fields are optional</strong></p>


      {% if form.non_field_errors %}
      <div class="alert alert-danger">{{ form.non_field_errors }}</div>
      {% endif %}

      <div class="form-group {% if form.acq_status.errors %}has-error{% endif %}">
        <label for="id_acq_status" class="col-sm-2 control-label">Acquired method</label>
        <div class="col-sm-5">
          {% render_field form.acq_status class+="form-control" %}
        </div>
      </div>
<!--
      <div class="form-group {% if form.species.errors %}has-error{% endif %}">
        <label for="id_species" class="col-sm-2 control-label">Species</label>
        <div class="col-sm-5">
          {% render_field form.species class+="form-control" %}
        </div>
      </div>-->

      <div class="form-group {% if form.sex.errors %}has-error{% endif %}">
        <label for="id_sex" class="col-sm-2 control-label">Sex</label>
        <div class="col-sm-5">
          {% render_field form.sex class+="form-control" %}
        </div>
      </div>

      <div class="form-group {% if form.nest.errors %}has-error{% endif %}">
        <label for="id_nest"url(r'^nests/$', views.NestList.as_view(), name='nests'), class="col-sm-2 control-label">Nest</label>
        <div class="col-sm-5">
          {% render_field form.nest class+="form-control" %}
        </div>
      </div> 

<!--      <div class="form-group {% if form.sire.errors %}has-error{% endif %}">
        <label for="id_sire" class="col-sm-2 control-label">Sire</label>
        <div class="col-sm-5">
          {% render_field form.sire class+="form-control" %}
        </div>
      </div>

      <div class="form-group {% if form.dam.errors %}has-error{% endif %}">
        <label for="id_dam" class="col-sm-2 control-label">Dam</label>
        <div class="col-sm-5">
          {% render_field form.dam class+="form-control" %}
        </div>
      </div>

      <!-- <div class="form-group {% if form.banding_date.errors %}has-error{% endif %}"> -->
      <!--   <label for="id_hatch_date" class="col-sm-2 control-label">Hatch date</label> -->
      <!--   <div class="col-sm-3"> -->
      <!--     <div class="input-group date" id="datetimepicker2"> -->
      <!--       {% render_field form.hatch_date class+="form-control" data-format="MM/dd/YYYY" %} -->
      <!--       <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span> -->
      <!--       </span> -->
      <!--     </div> -->
      <!--   </div> -->
      <!-- </div> -->

      <div class="form-group {% if form.alive.errors %}has-error{% endif %}">
        <label for="id_location" class="col-sm-2 control-label">Alive</label>
        <div class="col-sm-5">
          {% render_field form.alive class+="form-control" %}
        </div>
      </div>

      <!-- <div class="form-group {% if form.colorband.errors %}has-error{% endif %}"> -->
      <!--   <label for="id_colorband" class="col-sm-2 control-label">Band</label> -->
      <!--   <div class="col-sm-3"> -->
      <!--     {% render_field form.colorband class+="form-control" %} -->
      <!--   </div> -->
      <!-- </div> -->

      <div class="form-group {% if form.color1.errors %}has-error{% endif %}">
        <label for="id_color1" class="col-sm-2 control-label">Color1</label>
        <div class="col-sm-3">
          {% render_field form.color1 class+="form-control" %}
        </div>
      </div>
      <div class="form-group {% if form.band1.errors %}has-error{% endif %}">
        <label for="id_band1" class="col-sm-2 control-label">Band1</label>
        <div class="col-sm-3">
          {% render_field form.band1 class+="form-control" %}
        </div>
      </div>
      <div class="form-group {% if form.color2.errors %}has-error{% endif %}">
        <label for="id_color2" class="col-sm-2 control-label">Color2</label>
        <div class="col-sm-3">
          {% render_field form.color2 class+="form-control" %}
        </div>
      </div>
      <div class="form-group {% if form.band2.errors %}has-error{% endif %}">
        <label for="id_band2" class="col-sm-2 control-label">Band2</label>
        <div class="col-sm-3">
          {% render_field form.band2 class+="form-control" %}
        </div>
      </div>

      <div class="form-group {% if form.song_speed.errors %}has-error{% endif %}">
        <label for="song_speed_lessthan" class="col-sm-2 control-label">Song Speed &lt; </label>
        <div class="col-sm-5">
          {% render_field form.song_speed_lessthan class+="form-control" %}
        </div>
      </div>

      <div class="form-group {% if form.song_speed.errors %}has-error{% endif %}">
        <label for="song_speed_greaterthan" class="col-sm-2 control-label">Song Speed &gt; </label>
        <div class="col-sm-5">
          {% render_field form.song_speed_greaterthan class+="form-control" %}
        </div>
      </div>	  

      <div class="form-group {% if form.song_speed.errors %}has-error{% endif %}">
        <label for="call_speed_lessthan" class="col-sm-2 control-label">Call Speed &lt;</label>
        <div class="col-sm-5">
          {% render_field form.call_speed_lessthan class+="form-control" %}
        </div>
      </div>

      <div class="form-group {% if form.song_speed.errors %}has-error{% endif %}">
        <label for="call_speed_greaterthan" class="col-sm-2 control-label">Call Speed &gt; </label>
        <div class="col-sm-5">
          {% render_field form.call_speed_greaterthan class+="form-control" %}
        </div>
      </div>	  
      <div class="form-group {% if form.seqvar.errors %}has-error{% endif %}">
        <label for="seqvar" class="col-sm-2 control-label">Sequence Variability?</label>
        <div class="col-sm-5">
          {% render_field form.seqvar class+="form-control" %}
        </div>
      </div>	
      <div class="form-group {% if form.repeats.errors %}has-error{% endif %}">
        <label for="repeats" class="col-sm-2 control-label">Repeats?</label>
        <div class="col-sm-5">
          {% render_field form.repeats class+="form-control" %}
        </div>
      </div>		  

      <div class="form-group {% if form.location.errors %}has-error{% endif %}">
        <label for="id_location" class="col-sm-2 control-label">Location</label>
        <div class="col-sm-5">
          {% render_field form.location class+="form-control" %}
        </div>
      </div>

      <div class="form-group {% if form.user.errors %}has-error{% endif %}">
        <label for="id_reserved_by" class="col-sm-2 control-label">Reserved by</label>
        <div class="col-sm-3">
          {% render_field form.reserved_by class+="form-control" %}
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">Search</button>
        </div>
      </div>

    </form>
  </div>
</div>


<h2>Birds</h2>
{% if filter %}
    <form action="" method="get" class="form form-inline">
        {% bootstrap_form filter.form layout='inline' %}
        {% bootstrap_button 'filter' %}
    </form>
{% endif %}

{% render_table results %}

{% endblock %}

birds/templates/birds/egg_event_entry.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %} Colquitt lab : bird colony : add egg event {% endblock title%}



{% block content %}

<div class="panel panel-default">
  <div class="panel-heading"> 
    <h3 class="panel-title">New event</h3>
  </div>
  <div class="panel-body">
 {#<!--   <form action="{% url 'birds:eggs' egg.uuid %}" class="form-horizontal" method="post" role="form">-->#}
   <form action="{% url 'birds:egg_event' %}" class="form-horizontal" method="post" role="form">

      {% csrf_token %}
      <p><strong>Instructions</strong>: This form is for adding an egg event to the
        database. Events track each egg's life history and allow us to
        determine its current status and location. You can use the <a href="{%
        url 'admin:egg_event_add' %}">admin interface</a> to add events for
        other eggs, or edit existing events.</p>

      {% if form.non_field_errors %}
      <div class="alert alert-danger">{{ form.non_field_errors }}</div>
      {% endif %}

      <div class="form-group {% if form.animal.errors %}has-error{% endif %}">
        <label for="id_egg" class="col-sm-2 control-label">Egg *</label>
        <div class="col-sm-5">
          {% render_field form.egg class+="form-control" %}
        </div>
      </div>

      <div class="form-group {% if form.status.errors %}has-error{% endif %}">
        <label for="id_event" class="col-sm-2 control-label">Event type * </label>
        <div class="col-sm-5">
          {% render_field form.event class+="form-control" %}
        </div>
      </div>


      <div class="form-group {% if form.date.errors %}has-error{% endif %}">
        <label for="id_date" class="col-sm-2 control-label">Event date * </label>
        <div class="col-sm-3">
          <div class="input-group date" id="datetimepicker1">
            {% render_field form.date class+="form-control" data-format="MM/dd/YYYY" %}
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>

      <div class="form-group {% if form.location.errors %}has-error{% endif %}">
        <label for="id_location" class="col-sm-2 control-label">Location</label>
        <div class="col-sm-5">
          {% render_field form.location class+="form-control" %}
        </div>
      </div>

      <div class="form-group {% if form.description.errors %}has-error{% endif %}">
        <label for="id_description" class="col-sm-2 control-label">Description</label>
        <div class="col-sm-5">
          {% render_field form.description class+="form-control" rows="3"%}
        </div>
      </div>

      <div class="form-group {% if form.entered_by.errors %}has-error{% endif %}">
        <label for="id_entered_by" class="col-sm-2 control-label">Entered by * </label>
        <div class="col-sm-3">
          {% render_field form.entered_by class+="form-control" %}
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">Add event</button>
        </div>
      </div>

    </form>
  </div>
</div>

{% endblock %}

birds/templates/birds/eggs_entry.html
{% extends "base.html" %}

{% load static %}
{% load render_table from django_tables2 %}
{% load widget_tweaks %}
{% load bootstrap3 %}

{% block title %} Colquitt lab : bird colony : add eggs {% endblock title%}

{% block css %}
    <link href="{% static 'local/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
{% endblock %}

{% block scripts %}
<script src="{% static 'local/js/moment.min.js' %}"></script>
<script src="{% static 'local/js/bootstrap-datetimepicker.min.js' %}"></script>
<script type="text/javascript">
  $(function () {
  $('#datetimepicker1').datetimepicker({ pickTime: false});
  });
</script>
{% endblock %}


{% block content %}

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">New clutch of eggs</h3>
  </div>
  <div class="panel-body">
    <form action="{% url 'birds:new_eggs' %}" class="form-horizontal" method="post" role="form">
      {% csrf_token %}
      <p><strong>Instructions</strong>: Only enter clutches once the number of chicks
        is known. Enter the either the father and mother or the nest, the number of eggs, and the most likely date
        of birth. This will create records for the new birds and for the hatch events.
        You will need to manually set band information later, when the chicks are banded.
      </p>
      {% if form.non_field_errors %}
      <div class="alert alert-danger">{{ form.non_field_errors }}</div>
      {% endif %}

      <div class="form-group {% if form.nest.errors %}has-error{% endif %}">
        <label for="id_nest" class="col-sm-2 control-label">Nest</label>
        <div class="col-sm-5">
          {% render_field form.nest class+="form-control" %}
        </div>
      </div>

      <div class="form-group {% if form.sire.errors %}has-error{% endif %}">
        <label for="input-sire" class="col-sm-2 control-label">Sire</label>
        <div class="col-sm-5">
          {% render_field form.sire class+="form-control" %}
        </div>
      </div>

      <div class="form-group {% if form.dam.errors %}has-error{% endif %}">
        <label for="id_dam" class="col-sm-2 control-label">Dam</label>
        <div class="col-sm-5">
          {% render_field form.dam class+="form-control" %}
        </div>
      </div>

      <div class="form-group {% if form.lay_date.errors %}has-error{% endif %}">
        <label for="id_lay_date" class="col-sm-2 control-label">Lay Date</label>
        <div class="col-sm-3">
          <div class="input-group date" id="datetimepicker1">
            {% render_field form.lay_date class+="form-control" data-format="MM/dd/YYYY" %}
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>

      <div class="form-group {% if form.chicks.errors %}has-error{% endif %}">
        <label for="id_chicks" class="col-sm-2 control-label">Number of eggs</label>
        <div class="col-sm-3">
          {% render_field form.egg_number class+="form-control" %}
        </div>
      </div>

      <div class="form-group {% if form.comments.errors %}has-error{% endif %}">
        <label for="id_comments" class="col-sm-2 control-label">Comments</label>
        <div class="col-sm-5">
          {% render_field form.comments class+="form-control" rows="3"%}
        </div>
      </div>

      <div class="form-group {% if form.user.errors %}has-error{% endif %}">
        <label for="id_user" class="col-sm-2 control-label">Entered by</label>
        <div class="col-sm-3">
          {% render_field form.user class+="form-control" %}
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">Add Eggs</button>
        </div>
      </div>

    </form>
  </div>
</div>

<div class="panel-heading">
    <h3 class="panel-title">Egg info</h3>
</div>

{% if results %}
    {% render_table results %}
{% endif %}
{% endblock %}